language: python
python:
- '2.7'
script: nosetests
env:
  matrix:
    secure: dGISwfg6yRMlhKoAv7WFXZxRvMhCPYDITdMnJ+6P/BYHpodHaijEusdpR8IadVur8kDzvm6Arw47w/unphuyGa4S30D43iSFtBm6URFeFwEKx0t88hYAE9W4KZdNH5wQA86FVgQXGBItNlkA5c7E8XcpyrKJ1pngzUUIgRhevuk=
